### ISSUE TITLE
Date defaulting to '2015-11-28'

### ISSUE THREAD

**Issue by dieggsy** [deanishe/cookiecutter-alfred-workflow#1]
Hi there,

Wonderful little template you have here. I wanted to point out that the date is currently defaulting to "2015-11-28", not the current date. If this is intended behavior, is there a way I can insert the current date by default?

As always, thank you for all your help with alfred workflows.

**Comment by deanishe** [comment]
I'll look into it. It wasn't possible to use the date in cookiecutter [when I created the template](https://github.com/audreyr/cookiecutter/issues/428).

**Comment by deanishe** [comment]
I've updated the template to use the date macros in cookiecutter 1.4.

I had to remove the bundled `get-pip.py` (it didn't work any more), so you now have to have pip installed somewhere the system Python can import it from (the template uses `/usr/bin/python -m pip`).
